const message = {
    SUCCESS: {
        DATA_CREATED: "SUCCESSFULLY CREATED.",
        DATA_FETCHED: "DATA RETRIVED SUCCESSFULLY.",
        DATA_UPDATED: "DATA SUCCESSFULLY UPDATED.",
        DATA_DELETED: "DELETED SUCCESSFULLY."
    },
    ERROR: {
        NOT_FOUND: "RESOURECE NOT FOUND.",
        INVALID_INPUT: "INVALIDE INPUT PROVIDED.",
        SERVER_ERROR: "INTERNAL SERVER ERROR",
        EMAIL_EXISTS: "EMAIL ALREADY EXISTS."
    }
}

export default message